name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]   # common-directory의 main이 변경될 때 트리거

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2   # 이 레포 = common-directory를 체크아웃

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: creates output
        run: sh ./build.sh

      - name: Pushes to StudyApp repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.MY_TOKEN }}   # PAT: StudyApp에 push 권한 있어야 함
        with:
          source-directory: 'output'                  # build.sh 에서 만든 폴더
          destination-github-username: 'khy1121'      # ✅ 여기!
          destination-repository-name: 'StudyApp'     # ✅ 여기!
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
